### ISSUE TITLE
Choosing Docker runtime via inserting build command in Buildspec

### ISSUE THREAD

**Issue by dave-007** [awslabs/aws-devops-essential#26]
During this step in lab:

```
Add the Build stage:
...
    Select runtime as Docker
```
I don't have an option for Docker, so build fails.  To get this working, From AWS console I needed to:
In CodeBuild edit the **eks-build-project**, and choose Edit Buildspec, and chose insert build commands
I changed lines 12-17 to:

```
phases:
  install:
    runtime-versions:
      docker: 18
```
